
ingress:
  enabled: false

service:
  type: LoadBalancer
  port: 19999
  loadBalancerIP: 192.168.1.30


parent:
  nodeSelector:
    kubernetes.io/hostname: srv01

  database:
    storageclass: "local-path"
    volumesize: 30Gi

  alarms:
    storageclass: "local-path"
    volumesize: 3Gi

  claiming:
    enabled: true
    token: "okgF-H5xWDcO59Ix982VWQ0Q69b1e-RHlucesspy-TGZy0ee330vxc03mmfx8ACvMqSiRB0GS1ugjBw1pOwj8qPqUtcPTMq1lqBtjcCpGGZ3y80vk-nMpSmpnuz2GtbQMMad7vM"
    rooms: "4a83c604-b409-4805-b149-703576ea738d"
    url: "https://app.netdata.cloud"
