apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.images.backend.name}}:{{.Values.images.backend.tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
