apiVersion: v1
kind: ServiceAccount
metadata:
  name: authenticated-service-account
  namespace: tekton-pipelines
secrets:
  - name: github-secret
imagePullSecrets:
  - name: docker-registry-credentials
