kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-trigger-service-account
  namespace: tekton-pipelines
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
    verbs: ["get"]
  - apiGroups: [""]
    # secrets are only needed for Github/Gitlab interceptors
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["service-accounts"]
    verbs: ["impersonate"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-trigger-service-account
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-trigger-service-account
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-trigger-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-trigger-service-account
