global:
  hosts:
    domain: intra.bmw12.ch
    https: false
    gitlab:
      name: gitlab.intra.bmw12.ch
      https: false
    registry:
      name: registry.intra.bmw12.ch
      https: false
    minio:
      name: minio.intra.bmw12.ch
      https: false

  ingress:
    enabled: true
    configureCertmanager: false
    class: traefik
    tls:
      enabled: false

  psql:
    host: pg.intra.bmw12.ch
    port: 5432
    database: gitlab
    username: gitlab
    password:
      secret: gitlab-postgres
      key: postgres-password

  redis:
    host: redis-master
    password:
      enabled: true
      secret: redis
      key: redis-password


  grafana:
    enabled: false

  edition: ce

postgresql:
  install: false

redis:
  install: false


gitlab-runner:
  runners:
    privileged: true

certmanager:
  install: false

nginx-ingress:
  enabled: false
