apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-certificat
  namespace: cert-manager
spec:
  secretName: prod-certificat-tls
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt-prod
  dnsNames:
    - 'bmw12.ch'
    - '*.bmw12.ch'
    - '*.intra.bmw12.ch'
    - 'sircremefresh.ch'
    - '*.sircremefresh.ch'
    - '*.intra.sircremefresh.ch'
