apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cert-manager-clouddns-issuer
spec:
  acme:
    email: donato.wolfisberg@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: example-issuer-account-key
    solvers:
      - dns01:
          clouddns:
            project: sircremefresh
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
