apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: donato.wolfisberg@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: sircremefresh
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
