apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cluster-issuer-letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: donato.wolfisberg@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-letsencrypt-staging-account-key
    solvers:
      - dns01:
          clouddns:
            project: sircremefresh
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
