replicaCount: 1


# settings for enabling TLS
tls:
  enabled: true
  secret: "prod-bmw12-ch-tls"  # The name of a kubernetes.io/tls type secret to use for TLS
  CA:
    enabled: false

service:
  ldapPort: 389
  sslLdapPort: 636
  loadBalancerIP: ""
  type: LoadBalancer

# Default configuration for openldap as environment variables. These get injected directly in the container.
# Use the env variables from https://github.com/osixia/docker-openldap#beginner-guide
env:
  LDAP_ORGANISATION: "BMW12 Cluster"
  LDAP_DOMAIN: "ldap.intra.bmw12.ch"
  LDAP_BACKEND: "mdb"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "false"
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

initResources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
