name: sample-application
namespace: sample-application
images:
  backend:
    name: donatowolfisberg/sample-application-backend
    tag: 95f4f674795cab5629ecb5fe32b88fd318203d78
values:
  - values.yaml
