name: sample-application
namespace: sample-application
images:
  backend:
    name: donatowolfisberg/sample-application-backend
    tag: 33ace57a799c38af4e654d185cba3aaabcee155c
secrets:
  - secret-values.encrypted-yaml
values:
  - values.yaml
