name: sample-application
namespace: sample-application
images:
  backend:
    name: donatowolfisberg/sample-application-backend
    tag: 573568205467998a0184b16774baa55fb7f3f494
secrets:
  - secret-values.encrypted-yaml
values:
  - values.yaml
