name: potato-video
namespace: potato-video
images:
  backend:
    name: donatowolfisberg/potato-video
    tag: d8da8306a02e17f6bb15da197fe57e14ba5a915c
secrets:
  - database-secrets.encrypted-yaml
values:
  - values.yaml
