name: potato-video
namespace: potato-video
images:
  backend:
    name: donatowolfisberg/potato-video
    tag: a4b1086915e86e60960d347c1ad7d94e9449ed73
secrets:
  - database-secrets.encrypted-yaml
values:
  - values.yaml
