name: potato-video
namespace: potato-video
images:
  backend:
    name: donatowolfisberg/potato-video
    tag: 09af020f051b3350f606a8dbdb6c11279539abca
secrets:
  - database-secrets.encrypted-yaml
  - ctf-secrets.encrypted-yaml
values:
  - values.yaml
