name: potato-video
namespace: potato-video
images:
  backend:
    name: donatowolfisberg/potato-video
    tag: 8658a6b427d6694d0a899f2beaadd4aabb97744a
secrets:
  - database-secrets.encrypted-yaml
values:
  - values.yaml
