name: potato-video
namespace: potato-video
images:
  backend:
    name: donatowolfisberg/potato-video
    tag: 3fe8277304bbbb42bc2a3042693e12c9755dc40d
secrets:
  - database-secrets.encrypted-yaml
values:
  - values.yaml
