name: potato-video

images:
  backend:
    name: donatowolfisberg/potato-video
    tag: ''

apps:
  backend:
    name: potato-video-backend
    replicas: 1
    servicePort: 8080
    database:
      user: 'donato'
      host: 'pg.intra.bmw12.ch'
      port: '5432'
      password: ''
      databaseSecret: 'potato-video-database-secret'
    ctf:
      ctfSecret: 'potato-video-ctf-secret'
      flag: ''
    ingress:
      class: nginx
      url: potato-video-ctf.intra.bmw12.ch
