apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.bmw12.ch

  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: fe8d3d95f83b0e69c15a
          clientSecret: 23e07b956849247e0c00421f8c2e8fd43da898d5
          orgs:
          - name: bmw12IOT
