apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bmw12-image-updater-task
  namespace: tekton-pipelines
spec:
  params:
    - name: callbackUrl
      type: string
    - name: repoUrl
      type: string
    - name: imageName
      type: string
    - name: tag
      type: string
    - name: name
      type: string
    - name: namespace
      type: string
    - name: owner
      type: string
  resources:
    inputs:
      - name: chart-repo
        type: git
        targetPath: chart-repo
  steps:
    - name: build
      image: donatowolfisberg/bmw12-image-updater:b9dbf1c812b053b156d0506c227ed7bfd2dfa962
      command: [ "node", "/usr/src/app/dist/index.js" ]
      workingDir: "/workspace/chart-repo"
      args: [ "--git-email=donato@wolfisberg.dev", "--git-name=BMW12-CICD", "--workspace-path=/workspace/chart-repo", "--callback-url=$(params.callbackUrl)", "--repo-url=$(params.repoUrl)", "--image-name=$(params.imageName)", "--tag=$(params.tag)", "--name=$(params.name)", "--namespace=$(params.namespace)", "--owner=$(params.owner)" ]

