apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bmw12-deployer-task
  namespace: tekton-pipelines
spec:
  params:
    - name: commits
      type: string
  resources:
    inputs:
      - name: source
        type: git
        targetPath: chart-repo
  steps:
    - image: donatowolfisberg/bmw12-tekton-base-image:ea2c8205e235b0000e2a6857060a40297f3b8dc8
      script: |
        #! /bin/bash
        echo "$(params.commits)"
        echo "$(params.commits)" | jq ".commits[].modified|.[]"
        echo "hello"
        ls -al $(inputs.resources.source.path)
