apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bmw12-deployer-task
  namespace: tekton-pipelines
spec:
  params:
    - name: after
      type: string
    - name: before
      type: string
  steps:
    - image: donatowolfisberg/bmw12-tekton-base-image:8dd70fafef4b67f046375f0d1abdf31a03bb4ace
      workingDir: "/workspace"
      script: |
        #! /bin/bash
        pwd
        echo "start cloning"
        git clone https://github.com/SirCremefresh/bmw12-cluster.git
        if [ $? -ne 0 ]; then
          echo "Could not clone repository" 1>&2
          exit 2
        fi
        cd bmw12-cluster
        echo "$(params.before)"
        echo "$(params.after)"
        git diff --name-only "$(params.before)" "$(params.after)" | cat
        echo "hello"
