apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prod-bmw12-ch
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt-prod
  dnsNames:
    - 'bmw12.ch'
    - '*.bmw12.ch'
    - '*.intra.bmw12.ch'

