apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.backend.name }}
spec:
  selector:
    app: {{ .Values.apps.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.apps.backend.servicePort }}
      targetPort: 8080
