apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: bmw12-image-updater-task-run-17
  namespace: tekton-pipelines
spec:
  serviceAccountName: authenticated-serviceaccount
  taskRef:
    name: bmw12-image-updater-task
  params:
    - name: callbackUrl
      value: https://hub.docker.com/callback
    - name: repoUrl
      value: https://hub.docker.com/repo
    - name: imageName
      value: donatowolfisberg/sample-application-backend
    - name: tag
      value: testing_tag
    - name: name
      value: some_name
    - name: namespace
      value: some_namespace
    - name: owner
      value: some_owner
  resources:
    inputs:
      - name: chart-repo
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/SirCremefresh/bmw12-cluster.git
