apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-remover
  namespace: elk
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: alpine
              command: [ "/bin/sh","-c" ]
              args: [ "apk add curl && apk add coreutils && curl -XDELETE http://elasticsearch-es-http.elk:9200/logstash-`date -d'30 days ago' +'%Y.%m.%d'`" ]
              name: data-remover
          restartPolicy: Never
      backoffLimit: 2
