apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
spec:
  version: 7.9.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: true
      podTemplate:
        spec:
          nodeSelector:
            kubernetes.io/hostname: srv01
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 4Gi
                  cpu: 1
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
  volumeClaimTemplates:
   - metadata:
       name: elasticsearch-data
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 40Gi
       storageClassName: "local-path"
 http:
   service:
     spec:
       # expose this cluster Service with a LoadBalancer
       type: LoadBalancer
   tls:
     selfSignedCertificate:
       # add a list of SANs into the self-signed HTTP certificate
       subjectAltNames:
       - ip: 192.168.1.2
       - ip: 192.168.1.3
       - dns: elasticsearch-sample.example.com
     certificate:
       # provide your own certificate
       secretName: my-cert
