---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
  namespace: tekton-pipelines
spec:
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secretToken
            eventTypes:
              - push
        - cel:
            overlays:
              - key: branch_name
                expression: "body.ref.split('/')[2]"
        - cel:
            filter: "body.ref == 'refs/heads/master'"
        - cel:
            filter: "body.repository.full_name == 'SirCremefresh/bmw12-cluster'"
      bindings:
        - ref: github-pr-binding
      template:
        name: github-template
  serviceAccountName: tekton-trigger-service-account
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: before
      value: $(body.before)
    - name: after
      value: $(body.after)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrepositoryurl
    - name: before
    - name: after
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: bmw12-deployer-
        namespace: tekton-pipelines
      spec:
        serviceAccountName: authenticated-service-account
        taskRef:
          name: bmw12-deployer-task
        params:
          - name: after
            value: $(tt.params.after)
          - name: before
            value: $(tt.params.before)
