rbac:
  create: false

replication:
  enabled: false

image:
  tag: 12.4.0

service:
  type: LoadBalancer
  port: 5432
  loadBalancerIP: "192.168.1.21"

persistence:
  enabled: true
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 80Gi

updateStrategy:
  type: RollingUpdate

master:
  nodeSelector:
    kubernetes.io/hostname: srv01
