image:
  repository: bitnami/postgresql
  tag: 12.5.0-debian-10-r14

rbac:
  create: false

replication:
  enabled: false

service:
  type: LoadBalancer
  port: 5432
  loadBalancerIP: "192.168.1.21"

extendedConfConfigMap: 'extended-postgresql-config'

persistence:
  existingClaim: data-postgresql-postgresql-0
  enabled: true
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 80Gi

updateStrategy:
  type: RollingUpdate

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 4Gi
    cpu: 2048m


master:
  nodeSelector:
    kubernetes.io/hostname: srv01
