
postgresql:
  replicaCount: 2
  updateStrategyType: RollingUpdate

  resources:
    limits:
      cpu: 1500m
      memory: 1512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  pdb:
    create: false

  username: postgres

pgpool:
  replicaCount: 2

  resources:
    limits:
      cpu: 1500m
      memory: 1512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  pdb:
    create: false

  adminUsername: admin


ldap:
  enabled: false

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce

  size: 50Gi

service:
  type: LoadBalancer
  port: 5432
  loadBalancerIP: "192.168.1.21"

ingress:
  enabled: false

networkPolicy:
  enabled: true
  allowExternal: true

#
#metrics:
#  enabled: false
#
#  resources:
#    limits:
#      cpu: 250m
#      memory: 256Mi
#    requests:
#      cpu: 250m
#      memory: 256Mi
#
#  ## Annotations for Prometheus exporter
#  ##
#  annotations:
#    prometheus.io/scrape: "true"
#    prometheus.io/port: "9187"
#
#  ## Enable this if you're using Prometheus Operator
#  ##
#  serviceMonitor:
#    enabled: false
#    namespace: monitoring
#
#    selector:
#      prometheus: prometheus-server
